### ISSUE TITLE
What kind of data-augmentation?

### ISSUE THREAD

**Issue by youngwanLEE** [shicai/SENet-Caffe#2]
I wonder what kind of data-augmentation you used in training.

Thank you :)

**Comment by shicai** [comment]
scale & aspect ratio augmentation.

**Comment by 408550969** [comment]
caffe how to implement centre crop? The default is random crop
would you mind share train.prototxt? Thanks!

**Comment by shicai** [comment]
in test phase, center crop is the the default  setting.

**Comment by 408550969** [comment]
Thanks

**Comment by 408550969** [comment]
May I ask another question? 
What is the use of scale?I know it can adjust the value of data to 0-4.352

**Comment by shicai** [comment]
Lots of guys asked me this question.
You can find answers here: https://github.com/shicai/MobileNet-Caffe/issues/17
(If you are Chinese, you can also take a look at this link: https://www.zhihu.com/question/63649386/answer/211508137)

**Comment by 408550969** [comment]
Thanks!

**Comment by miraclewkf** [comment]
You only use scale and aspect ratio augmentation in training? What is the parameter of aspect ratio you set? You don't use random_mirror in training?

**Comment by miraclewkf** [comment]
One more question, do you resize the original image to one size (for example, resize shorter side to 256) before other data argumentations during training?
