### ISSUE TITLE
scale & mean_values

### ISSUE THREAD

**Issue by whria78** [shicai/SENet-Caffe#6]
Hello, thank you for the SENet model.

I saw the following codes,

```
#  transform_param {
#    scale: 0.017
#    mirror: false
#    crop_size: 225
#    mean_value: [103.94,116.78,123.68]
# }

```

Is it better to use

"scale: 0.017 , mean_value [103.94,116.78,123.68]"

as it is, when I fine-tune the model ?

**Comment by shicai** [comment]
yes.
